"""initial doctor models

Revision ID: 7ed6c9e87aad
Revises: 
Create Date: 2026-08-19 17:50:58.267392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed6c9e87aad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_facebook_id_key'), 'users', type_='unique')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_facebook_id_key'), 'users', ['facebook_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
