"""describe your change_05

Revision ID: 845dddc0dbb9
Revises: cb1d1cd3e6b1
Create Date: 2026-08-22 01:02:10.754459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845dddc0dbb9'
down_revision: Union[str, None] = 'cb1d1cd3e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
