"""describe your change_08

Revision ID: 8c80aaa058fb
Revises: c1b0a53dbe7b
Create Date: 2026-09-07 20:52:46.857833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c80aaa058fb'
down_revision: Union[str, None] = 'c1b0a53dbe7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('payment_intent_id', sa.String(length=255), nullable=False))
    op.add_column('appointments', sa.Column('status', sa.String(length=20), server_default='confirmed', nullable=False))
    op.drop_index(op.f('ix_appointments_payment_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_payment_intent_id'), 'appointments', ['payment_intent_id'], unique=True)
    op.drop_column('appointments', 'payment_id')
    op.drop_column('appointments', 'payment_provider')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.add_column('appointments', sa.Column('payment_provider', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_appointments_payment_intent_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_payment_id'), 'appointments', ['payment_id'], unique=True)
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'payment_intent_id')
    # ### end Alembic commands ###
