"""describe your change_07

Revision ID: 8ca71289bfde
Revises: a1c5b03e9f31
Create Date: 2026-09-04 00:11:03.412780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca71289bfde'
down_revision: Union[str, None] = 'a1c5b03e9f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'appointments',
        sa.Column(
            'payment_intent_id',
            sa.String(length=255),
            nullable=True
        )
    )

    op.create_index(
        op.f('ix_appointments_payment_intent_id'),
        'appointments',
        ['payment_intent_id'],
        unique=True
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_appointments_payment_intent_id'),
        table_name='appointments'
    )
    op.drop_column('appointments', 'payment_intent_id')
    # ### end Alembic commands ###
