"""describe your change_02

Revision ID: c255f0ca8b3d
Revises: 48ff8157ed38
Create Date: 2026-08-21 19:22:02.600257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c255f0ca8b3d'
down_revision: Union[str, None] = '48ff8157ed38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
