"""describe your change_06

Revision ID: fb3a4a1e3bf8
Revises: 845dddc0dbb9
Create Date: 2026-08-23 01:10:53.925775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3a4a1e3bf8'
down_revision: Union[str, None] = '845dddc0dbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_availability', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('doctor_availability', 'month')
    op.drop_column('doctor_availability', 'day_of_week')
    op.drop_column('doctor_availability', 'year')
    op.add_column('doctors', sa.Column('average_rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'average_rating')
    op.add_column('doctor_availability', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('doctor_availability', sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('doctor_availability', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('doctor_availability', 'date')
    # ### end Alembic commands ###
